version: '3.8'
services:
  websocket:
    build: .
    container_name: game-websocket
    restart: unless-stopped
    tty: true
    networks:
      - game_network

  caddy:
    image: caddy:2
    container_name: game-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./test-websocket.html:/var/www/test-websocket.html
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - game_network

networks:
  game_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
